### ISSUE TITLE
OMERO 4 images and webtagging

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#10]
Happened today on nightshade (OMERO 5.0.4 release server).
Michael navigated to a dataset consisting of images imported in OMERO 4 and went to ``Auto Tag``.
He repeatedly tried to click ``Path``, ``Apply`` and ``Refresh`` buttons as well as opening the images in full viewer. After some time, he got Internal server error. The server needed to be restarted. 
/cc @will-moore 
@dpwrussell The logs can be gotten from @kennethgillen (he has Blitz and OMEROweb) - please ask him for what you need.

**Comment by dpwrussell** [comment]
Closing for now as there is no route for me to investigate it. If this reoccurs, please report.
