### ISSUE TITLE
403 after Apply

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#16]
- Login as Admin, go to your own or someone else's data (the same behaviour) in a Read-only group (can use user-6 on trout merge)
  - Select the Auto Tag option in central pane -> all looks as expected
  - Press "Apply"
  - you will see 
![screen shot 2015-03-18 at 11 26 36](https://cloud.githubusercontent.com/assets/2478303/6707732/accfe592-cd61-11e4-95c7-fa15d0a5bce2.png)

**Comment by pwalczysko** [comment]
@dpwrussell Note that also click on "New/Existing Tag" does nothing on trout merge.

**Comment by dpwrussell** [comment]
@pwalczysko I've just tried to replicate this locally without success. Some underlying 5.1 change may have fixed it potentially? I can't test on trout at the moment because I don't have VPN access.

**Comment by pwalczysko** [comment]
This is fixed, sorry.
