### ISSUE TITLE
ImageWrapper overriding leads to an infinite loop

### ISSUE THREAD

**Issue by joshmoore** [MicronOxford/webtagging#27]
See: 

 * https://github.com/MicronOxford/webtagging/blob/a3c03b07ccd7fc6a917bc61805461a0deaa43e2d/autotag/utils.py#L118 (current master)
 * https://github.com/openmicroscopy/openmicroscopy/pull/3688
 * https://github.com/aleksandra-tarkowska/openmicroscopy/commit/0c70f04d345ba0d3cbe2d64ff91471e9a81c3366
 * https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration-web/lastCompletedBuild/testReport/test.integration.test_csrf/TestCsrf/test_copy_past_rendering_settings/

The method inheritance here is leading to infinite recursion when webtagging is deployed and a share is used. In general, the `refreshWrappers` method has **very** limited scope/testing:
```
$ git grep refreshWrappers
OmeroPy/src/omero/gateway/__init__.py:def refreshWrappers():
OmeroPy/src/omero/gateway/__init__.py:refreshWrappers()
OmeroWeb/omeroweb/webclient/webclient_gateway.py:omero.gateway.refreshWrappers()
```
and another strategy (incl. supplying this method upstream) should be considered.

**Comment by joshmoore** [comment]
Any thoughts on workarounds @dpwrussell?

**Comment by dpwrussell** [comment]
@joshmoore Sorry for delay.

I was always rather uncomfortable with the `refreshWrappers` usage as it felt quite brittle. I mostly just copied the usage from @will-moore so I don't really have any answers on how to fix that.

There is only functionality being added to the `ImageWrapper` here though, not overridden. So I could very easily do away with the `refreshWrappers` and the sub-class `ImageWrapper` completely in favour of a utility function that does the same work. I'll do that if there is no consensus in any following discussion on what to do about `refreshWrappers`.

**Comment by joshmoore** [comment]
In discussion with @chris-allan, seems it's safest to assume these are internal methods only.
