### ISSUE TITLE
local variable 'additions' referenced before assignment

### ISSUE THREAD

**Issue by will-moore** [MicronOxford/webtagging#28]
From QA on ome demo server: https://www.openmicroscopy.org/qa2/qa/feedback/11006/
Web Bug 5.1.0-ice35-b40

"Trying to use auto tag on demo server, clicking Apply leads to 500 error https://demo.openmicroscopy.org/webtagging/auto_tag/processUpdate/"

```
File "/home/demo/web-extensions/webtagging/views.py", line 721, in process_update
successfulUpdates = {'additions': additions, 'removals': removals}
UnboundLocalError: local variable 'additions' referenced before assignment
path:/webtagging/auto_tag/processUpdate/,
```

**Comment by dpwrussell** [comment]
I'm not really sure how this could have happened. It is a minor bug which I have fixed in #32, but unless their was a non-post AJAX call, it can't really happen. processUpdate should always be called with a POST.

Can you recreate?
