### ISSUE TITLE
"Choose tags" tip misformatted

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#36]
See https://github.com/openmicroscopy/openmicroscopy/pull/3995#issuecomment-139534416 point 2.
Details: Use Firefox, e.g. 41.0, 40.0.3 on Mac and 40.0.3 on Win7 all have this problem. Also IE 11.0.23 on Win7 has this problem. Chrome does not have this problem (neither Win nor Mac).

@will-moore found out that the problem is in the ``padding`` in the ``Style`` of the element when inspected by Firebug. 
  - open Firebug
  - select the Choose Tag box
  - observe in the bottom right corner, undert the tab Style that when
  - you find the line saying ``padding: 5px;`` and switch it on and off, the misformatting of the text ``Choose Tags`` is going away/is restored
  - the problem with the ``Choose Tags`` text still being too much to the left can be alleviated by inputting ``margin: 5px;`` (originally,  the margin is zero)

**Comment by dpwrussell** [comment]
Closing as not an issue in 2.0.
