### ISSUE TITLE
tagsearch user dropdown doesn't work

### ISSUE THREAD

**Issue by jburel** [MicronOxford/webtagging#38]
Reported using the current release version

Go to `Tag Search` on nightshade or eel. Click on the user dropdown (`user-1 user-1`) in the top right corner. It doesn't work.

Browser: Firefox 42.0, Mac OS X 10.10.5

<img width="1121" alt="screen_shot_2015-12-03_at_16 49 14" src="https://cloud.githubusercontent.com/assets/1022396/12289495/c5eb00c0-b9d3-11e5-8f15-61841741877c.png">

**Comment by dpwrussell** [comment]
I can't replicate this. Still an issue?

**Comment by jburel** [comment]
not an issue anymore 
Closing
