### ISSUE TITLE
Selecting the pink bubble should be enough

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#39]
![screen shot 2016-01-15 at 15 29 42](https://cloud.githubusercontent.com/assets/2478303/12356882/d819649c-bb9c-11e5-8089-08fc11887a18.png)
At present, the user must select the arrow in the right-hand side of the pink bubble.
It would be more user-friendly to click anywhere into the bubble and the menu would pop down.

**Comment by dpwrussell** [comment]
I've thought about this and I'm not sure that I agree. The pink bubble is a placeholder for the blue bubble which represents a tag. The established functionality in the rest of webclient is to goto the tag in the tag view when clicked. Removing the tag requires clicking on the cross in the same way that clicking on the arrow opens the menu.

We can reopen this issue again later if you feel really strongly about it, but I think that this is the correct behaviour.

**Comment by pwalczysko** [comment]
@dpwrussell : Ah, sorry, the concept of this being ``ghost tags`` was completely lost on me.
But this is precisely the worrying point, as:
   - experienced user, 2nd time webtagging user etc. will not need any such concepts, they will know where to click
   - on a first-time user, this concept is far too complicated, and yet, this is the one which needs some help

Maybe give some textual hint about where to click (the advantage in webtagging is that you have space, whereas the tags in webclient are squeezed among other functionalities)

**Comment by dpwrussell** [comment]
I've never heard of anyone having a problem with that, but I guess there is no real harm in implementing it as I can't see any tidy way to give the hint to click that without horribly cluttering the interface.

**Comment by dpwrussell** [comment]
Fixed in eea3db4
