### ISSUE TITLE
Ignore first and ignore last does nothing

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#41]
Have a set of images named as in screenshot below (rename then PRIOR to import to OMERO):
![screen shot 2016-01-15 at 16 34 26](https://cloud.githubusercontent.com/assets/2478303/12358609/f82e9474-bba5-11e5-8750-fa1ec5b73e4b.png)

In Auto Tag, there are two tickboxes: ``Ignore first file token`` and ``Ignore last file token``. They do not seem to have any effect on the columns displayed (it should have fist and last columns ignored).

![screen shot 2016-01-15 at 16 34 34](https://cloud.githubusercontent.com/assets/2478303/12358736/a2b8f4ca-bba6-11e5-99ea-54fdf205e7fd.png)

**Comment by dpwrussell** [comment]
Closing as this is not an issue with 2.0.
