### ISSUE TITLE
Rename tickbox "Show unmapped"

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#42]
![screen shot 2016-01-20 at 11 18 07](https://cloud.githubusercontent.com/assets/2478303/12447345/86a59f94-bf67-11e5-863b-e305a679bb4f.png)

In order to give some lead about where to start to the first time user, rename the "Show unmapped" tickbox to "Create Tag". No need to be too precise, this should just give a lead to a first-timer, who needs to start somewhere.  Two things are needed.

   1. Rename it
   2. Make it bigger/bolder

**Comment by pwalczysko** [comment]
cc @will-moore

**Comment by dpwrussell** [comment]
I think I might call it "Show All Potential Tags" instead of "Create Tags". I just don't feel that "Create Tags" makes sense as that suggests that by clicking this, tags will be created which they will not unless tokens are then mapped.

**Comment by pwalczysko** [comment]
Makes sense to me.
