### ISSUE TITLE
Image with no fileset does not show up

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#45]
Create a new image using omero scripts. This image will be ignored by webtagging.
![screen shot 2016-01-20 at 11 31 59](https://cloud.githubusercontent.com/assets/2478303/12447745/943f3bfe-bf69-11e5-99b5-58c161f032d7.png)

@will-moore suggests this might be due to the lack of ``path`` which such image (with no fileset) has.

**Comment by dpwrussell** [comment]
@pwalczysko Yes, this image doesn't have a clientPath. So there is nothing for webtagging to process. Conceivably it could be shown in the table anyway, but that doesn't really make sense either so this is correct functionality.

**Comment by pwalczysko** [comment]
@dpwrussell : Maybe you could parse the tokens from the name then ? (path is not there, but the name is...)
