### ISSUE TITLE
Too many images error

### ISSUE THREAD

**Issue by gusferguson** [MicronOxford/webtagging#48]
@dpwrussell 
When testing auto tagging on cowfish with web merge.

Was in Autotag in centre pane with about 10 images selected - selected dataset in Data Tree with 250 images. Error message with:

Bad Request
    Request Line is too large (4270 &gt; 4094)

I think this error should be handled with a warning dialog.

**Comment by dpwrussell** [comment]
This is a problem `limit_request_line` in gunicorn. Potentially (although it does not philosophically agree with REST) I will switch to using POST for any requests like this which have a large input component. I will address that.

**Comment by dpwrussell** [comment]
@gusferguson Could you test this again once web merge is rebuilt with these changes to confirm I have fixed this issue? Cheers.

**Comment by gusferguson** [comment]
@dpwrussell 

Tested with https://cowfish.openmicroscopy.org/merge/webclient/ user-3 read-only-1

Can now select dataset with 250 images in data tree while in Auto Tag in centre pane.
All 250 images show in centre pane, no error.
Behaves as expected.
Good to merge.

**Comment by dpwrussell** [comment]
Thanks @gusferguson
