### ISSUE TITLE
Tooltip Help

### ISSUE THREAD

**Issue by dpwrussell** [MicronOxford/webtagging#51]
@pwalczysko @will-moore I've added tooltip help for the slider and the show unmapped text. I'd appreciate it if you could give me some feedback on the wording and if it requires revision.

Also, I've put the tooltip on the text as I found it annoying when it was on the slider/checkbox itself. The third option is to add a little icon (question mark) which is explicitly to show this tip. Thoughts?

**Comment by will-moore** [comment]
Tooltip suggestion: "Hide columns if token is found on fewer than this number of images".
Or  "Hide columns if token is found on fewer than n images".

**Comment by will-moore** [comment]
I think it would be slightly nicer to have a (?) icon beside the slider, and this icon showed the tooltip.
It might work better to have the number beside the "Rarity Threshold" text. E.g. (ascii art):
``` Rarity Threshold: 2  -----O----------------  (?) ```
