### ISSUE TITLE
Slight misalignment of slider and text

### ISSUE THREAD

**Issue by dpwrussell** [MicronOxford/webtagging#52]
@will-moore Any chance you could have a look at this? I can't seem to make the slider and associated text line up vertically with the other components in the toolbar.

**Comment by will-moore** [comment]
I don't know the "right" way to fix this, but this seems to look OK...
Add the following styles to the slider input:
```
    margin-top: -1px;       # stops the slider pushing the outer <span> element down
```
Then if you want to move the slider back down, you can add
```
    position: relative;
    bottom: -3px;
```

<img width="745" alt="screen shot 2016-01-27 at 23 42 34" src="https://cloud.githubusercontent.com/assets/900055/12632428/befd458e-c54f-11e5-83cd-470b0c33d9f3.png">

Hope that helps. You can always tweak the values to get what you want. Hopefully this works across browsers (not tested).

**Comment by dpwrussell** [comment]
Thanks, CSS is my nemesis.
