### ISSUE TITLE
Selecting Datasets with "unexpected" names crashes Autotagger

### ISSUE THREAD

**Issue by pwalczysko** [MicronOxford/webtagging#54]
Select a Dataset where the names of images start with a number
(e.g. two images in an orphaned dataset with names ``438CTR_01_4_R3D_D3D.dv`` and ``438CTR_01_5_R3D_D3D.dv``). The Autotagger will show only blank central pane. See screenshot and debugger info below.
Also note, after you have this error, no switching to other Datasets will relieve the problem, even refreshing the browser is not enough in some cases.

```
TypeError: this.props.tag.owner is undefined
https://frog.o...py.org/static/autotag/js/bundle.min.js
Line 29
```
![screen shot 2016-07-18 at 12 23 27](https://cloud.githubusercontent.com/assets/2478303/16913472/7a99d0cc-4ce2-11e6-9ae7-20d276497ba8.png)

**Comment by dpwrussell** [comment]
This does not seem related to filenames starting with numbers, or at least not exclusively so, as I can not reproduce this error.

@pwalczysko If you manage to reproduce this, please let me know and we can reopen this.

**Comment by pwalczysko** [comment]
Kenny had reinstalled  the Pillow as it was at the time when this Bug has demonstrated.
His workflow was:
```
Currently have Pillow==3.3.0  
in frog.o.org (which did not demonstrate the bug, PW)
Running `pip install "Pillow<3.0"`
as per requirements.txt
restart the web server
```
And this did not demonstrate the bug either. I guess we have to conclude "Cannot repeat at all." Sorry @dpwrussell
